
openapi: 3.0.3
info:
  title: SUPhoto
  description: |-
    Сервис для обмена фотографиями с мероприятий.
 

  contact:
    email: nirku0soft@yandex.ru
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
  
servers:
  - url: http://localhost:8080/



paths:
  /events:
    get:
      description: Получить список всех мероприятий
      operationId: getAllEvents
      tags:
        - CRUD
      parameters: 
        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/limitParam'
      responses: 
        200: 
           description: Ответ со списком мероприятий
           content: 
             application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/eventDTO'
                          
    post:
      description: Метод для создания нового мероприятия
      operationId: createEvent
      tags:
        - CRUD
      requestBody:
        description: Новое событие(id игнорируется)
        required: true
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/eventDTO' 
      responses: 
        201:
          description: Событие успешно сохранено. Возвращает сохраненную сущность с присвоенным ID
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/eventDTO'
        400: 
          $ref: '#/components/responses/validationErrorResponse'
              
  /events/{eventID}:
    put:
      description: Обновление сущности
      operationId: updateEvent
      tags:
        - CRUD

      parameters: 
        - name: eventID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      
      requestBody:
        description: Обновленное событие
        required: true
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/eventDTO'

      responses: 
        200:
          description: Событие успешно сохранено
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/eventDTO'
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

        400: 
          $ref: '#/components/responses/validationErrorResponse'

    get:
      description: Найти сущность по ID
      operationId: findEventById
      tags:
        - CRUD

      parameters: 
        - name: eventID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        200:
          description: Сущность с заданным ID найдена
          content: 
            application/json: 
              schema:
                $ref: '#/components/schemas/eventDTO'
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

    delete:
      description: Удалить сущность по ID
      operationId: deleteEventById
      tags:
        - CRUD

      parameters: 
        - name: eventID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        204:
          description: Сущность с заданным ID удалена
          
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

  /trainers:
    get:
      description: Получить список всех инструкторов
      operationId: getAllTrainers
      tags:
        - CRUD
      parameters: 
        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/limitParam'
      responses: 
        200: 
           description: Ответ со списком инструкторов
           content: 
             application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/trainerDTO'
                          
    post:
      description: Метод для создания нового инструктора
      operationId: createTrainer
      tags:
        - CRUD
      requestBody:
        description: Новый инструктор(id игнорируется)
        required: true
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/trainerDTO' 
      responses: 
        201:
          description: Сущность успешно сохранена. Возвращает сохраненную сущность с присвоенным ID
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/trainerDTO'
        400: 
          $ref: '#/components/responses/validationErrorResponse'

  /trainers/{trainerID}:
    put:
      description: Обновление сущности
      operationId: updateTrainer
      tags:
        - CRUD
      parameters: 
        - name: trainerID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      
      requestBody:
        description: Обновленная сущность
        required: true
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/trainerDTO'

      responses: 
        202:
          description: Инструктор успешно сохранен
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/trainerDTO'
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

        400: 
          $ref: '#/components/responses/validationErrorResponse'

    get:
      description: Найти сущность по ID
      operationId: findTrainerById
      tags:
        - CRUD

      parameters: 
        - name: trainerID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        200:
          description: Сущность с заданным ID найдена
          content: 
            application/json: 
              schema:
                $ref: '#/components/schemas/trainerDTO'
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

    delete:
      description: Удалить сущность по ID
      operationId: deleteTrainerById
      tags:
        - CRUD

      parameters: 
        - name: trainerID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        204:
          description: Сущность с заданным ID удалена
          
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

  /trainers/{trainerID}/events:
    get:
      description: Получить список мероприятий инструктора
      operationId: getAllEventsOfTrainer
      tags:
        - Logic
      
      parameters:
        - name: trainerID
          required: true
          in: path
          schema:
            type: integer
            format: int64

        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/limitParam'

      responses:
        200:
          description: Список ID мероприятий с учетом ограничений
          content: 
            application/json: 
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/ID'
        404:
          $ref: '#/components/responses/entityNotFoundResponse'


    post:
      description: Записать инструктора на мероприятие
      operationId: inviteTrainerToEvent
      tags:
        - Logic
      parameters:
        - name: trainerID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      requestBody:
        description: ID мероприятия
        required: true
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/ID'

      responses:
        202:
          description: Инструктор записан на мероприятие
        406:
          description: Инструктор уже записан на мероприятие
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

    delete:
      description: Отменить запись инструктора на мероприятие
      operationId: kickTrainerFromEvent
      tags:
        - Logic
      parameters:
        - name: trainerID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      requestBody:
        description: ID мероприятия
        required: true
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/ID'

      responses:
        204:
          description: Запись на мероприятие отменена
        406:
          description: Инструктор не записан на мероприятие
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

  /events/{eventID}/trainers:   
    get:
      description: Получить список инструкторов мероприятия
      operationId: getAllTrainersOfEvent
      tags:
        - Logic
      
      parameters:
        - name: eventID
          required: true
          in: path
          schema:
            type: integer
            format: int64

      responses:
        200:
          description: Список ID инструкторов с учетом ограничений
          content: 
            application/json: 
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/ID'
        404:
          $ref: '#/components/responses/entityNotFoundResponse'


    post:
      description: Записать инструктора на мероприятие
      operationId: addTrainerToEvent
      tags:
        - Logic
      parameters:
        - name: eventID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        description: ID инструктора
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/ID'

      responses:
        202:
          description: Инструктор записан на мероприятие
        406:
          description: Инструктор уже записан на мероприятие
        404:
          $ref: '#/components/responses/entityNotFoundResponse'

    delete:
      description: Отменить запись инструктора на мероприятие
      operationId: removeTrainerFromEvent
      tags:
        - Logic
      parameters:
        - name: eventID
          required: true
          in: path
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        description: ID инструктора
        content: 
          application/json: 
            schema:
              $ref: '#/components/schemas/ID'

      responses:
        204:
          description: Запись на мероприятие отменена
        406:
          description: Инструктор не записан на мероприятие
        404:
          $ref: '#/components/responses/entityNotFoundResponse'


components:
  schemas:   
    eventDTO:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 123
          title:
              type: string
              example: Прогулка по реке Сок
          location:
              type: string
              example: село Старосемейкино
          startTime:
              type: string
              format: date-time
              example: 2005-08-09T18:31:42+03
          endTime:
              format: date-time
              type: string
              example: 2005-08-09T18:31:42+03
    ID:
      type: object
      description: Идентификатор
      properties: 
        id:
          type: integer
          format: int64
          example: 123

    trainerDTO:
      type: object
      properties:
        id:
          type: number
          example: 123
        username:
          type: string
          example: fizlrock
        firstname:
          type: string
          example: Никита
        lastname:
          type: string
          example: Кукурузин
        patronymic:
          type: string
          example: Бетонович
        
    
    wrongField:
      type: object
      properties:
        fieldName:
          type: string
          example: trainer.username
        errorDescripion:
          type: string
          example: To long

  parameters:
    skipParam:
      name: skip
      in: query
      description: Номер элемента, с которого нужно начать.
      required: true
      schema:
        type: integer
        format: int32
        minimum: 0
    limitParam:
      name: limit
      in: query
      description: Максимально число элеметов.
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1


  responses: 
    validationErrorResponse:
      description: Переданы недопустимые параметры
      content:
        application/json:
          schema: 
            type: array
            items:
              $ref: '#/components/schemas/wrongField'

    entityNotFoundResponse:
      description: Сущность с таким ID не найдена

            
                 
        
    



